global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']
  - job_name: 'kubernetes'
    static_configs:
      - targets: ['kubernetes.default.svc.cluster.local']